### PR TITLE
Addressed a potential issue in build automation script

### PR DESCRIPTION
**Pull request by moodmosaic**
On my machine, the _build-release.sh_ script yields the following error which prevents the unit tests from running:

```
"\Exude\BuildRelease.msbuild" (default target) (1) ->
(Test target) ->
  \Exude\BuildRelease.msbuild(28,5): error : 
      The xunit task requires either Assembly or Assemblies, but not both.

    0 Warning(s)
    1 Error(s)
```

To make the unit tests run, I changed the _Build.config_ file to point in the _Exude.UnitTests_ folder location.

---

To reproduce this you have to invoke the _git clean_ command prior to running the _build-release.sh_ script (or make a fresh _git clone_ of the repository).

### CODE REVIEW

**Comment by sgryt** [comment]
Hi Nikos - thanks for pointing this out. We've found it to be a transient problem with MSBuild path expansions. MSBuild runs the path expansions before the build step, so if the binaries do not exist on disk when invoking MSBuild, we end up with empty paths for the test assembly, thus triggering the error. One workaround is to execute the _build-release.sh1_ script twice (at least on the machines we have tested it with) when starting from a clean state (aka no binary output on disk). 

Have you tested the new version on a clean directory (where the assemblies you point out in the revised version do not yet exist when invoking the script)? I seem to get the same error with the revised version (when running on a clean directory).

**Comment by moodmosaic** [comment]
Hi Mikkel! Yes indeed, if I do:

```
git clean -d -x -f
git checkout .
```

and run the _build-release.sh_ script, the first time it fails, and then it runs (even with the proposed changes).

I am going to close this Pull Request.

---

Wouldn't be possible to use the build scripts from Albedo? AFAICT this problem doesn't seem to exist there.

**Comment by ploeh** [comment]
Albedo uses an xUnit.net project file instead of a convention-based scan. I prefer the convention-based scan, because there's less maintenance involved (although I do realize that it includes the risk that a test assembly rename may pull an entire test suite out of the build process).

Once upon a time, @sgryt hinted to me that he once had a fix for this MSBuild issue, but that he forgot what it was...

**Comment by sgryt** [comment]
Possibly - I haven't looked at those. Will try a bit later on.

**Comment by sgryt** [comment]
Yeah, it includes some nasty reformatting tricks on '**' expansion characters in MSBuild Items. And defining some additional Xml elements in the Build.config. Yak shaving all along. Will look into digging out the examples I've worked on previously, but I'm afraid they went AWOL with the Safewhere ship.

**Pull request closed without merging**
