### PR TITLE
Static class support

### PR DESCRIPTION
**Pull request by moodmosaic**
This hopefully addresses #18.

Please notice that, in the files changed, the new `ITestCommand` is almost identical to the `FirstClassCommand` with the only difference that `ShouldCreateInstance` returns false.

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your contribution.

As far as I can tell, the proposed `StaticFirstClassCommand` class is almost identical to the existing `FirstClassCommand` class, apart from the `ShouldCreateInstance` property.

Wouldn't it be simpler to make it possible to pass a boolean flag to the constructor of `FirstClassCommand`?

**Comment by moodmosaic** [comment]
In the beginning I thought about adding a boolean flag but then I thought that it will probably make the API harder to understand.

OTOH the new class introduces a lot of duplication both in the class itself and in the tests :$

I will try to add a boolean flag and see where it goes.

**Comment by ploeh** [comment]
> it will probably make the API harder to understand.

Why? While `FirstClassCommand` is a public class, users aren't really supposed to have to deal with it.

**Comment by moodmosaic** [comment]
Yes, indeed. Well, this clearly demonstrates how an Exude-newbie I am... :$

**Comment by moodmosaic** [comment]
How about providing a default value in the signature?

```
public FirstClassCommand(
  Action<object> testAction,
  IMethodInfo testMethod,
  bool shouldCreateInstance = true)
```

The value for _shouldCreateInstance_ is by default true. In case of a static class I will explicitly pass false.

**Comment by moodmosaic** [comment]
Now that I am thinking of it again, I think it's better to do it as:

```
public FirstClassCommand(
    Action<object> testAction,
    IMethodInfo testMethod)
    : this(testAction, testMethod, true)
{
}

public FirstClassCommand(
    Action<object> testAction,
    IMethodInfo testMethod,
    bool shouldCreateInstance)
    : base(testMethod, null, -1)
{
    if (testAction == null)
        throw new ArgumentNullException("testAction");

    this.testAction = testAction;
    this.shouldCreateInstance = shouldCreateInstance;
}
```

It's probably not a big deal but I would like to keep the existing tests, that use the SUT's constructor, intact.

**Comment by ploeh** [comment]
Yes, please, to the second option. It may be irrational of me, but I severely dislike optional parameters.

However, I don't think there's a good default value for this. Only the creator of `FirstClassCommand` knows what the correct value is, or am I mistaken? Is there any reason why `true` is a better default value than `false`?

**Comment by moodmosaic** [comment]
Agreed about optional parameters. That's why I was skeptical about them :)

There isn't a good default value for this. The only reason I would chain the constructors with a default value is to keep the changes in existing unit tests to the minimum.

(Otherwise, I would have to go on each unit test that uses the constructor and pass a dummy boolean.)

**Comment by moodmosaic** [comment]
Closing this in order to replace it with #20.

**Pull request closed without merging**
